# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161206062041 on 2016-12-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepointer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedfiles',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
