# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161011124616 on 2016-10-11 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharepointer', '0003_auto_20161011_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='/uploads')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
