# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161011124616 on 2016-10-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepointer', '0004_fileentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentity',
            name='no_of_times_views',
            field=models.IntegerField(default=0),
        ),
    ]
