# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161017123123 on 2016-10-17 13:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharepointer', '0005_fileentity_no_of_times_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='uploads'))),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='FileEntity',
        ),
        migrations.CreateModel(
            name='ReceivedFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sharepointer.FileModel')),
            ],
            bases=('sharepointer.filemodel',),
        ),
        migrations.CreateModel(
            name='SentFile',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sharepointer.FileModel')),
            ],
            bases=('sharepointer.filemodel',),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
